### ISSUE TITLE
Datasets Downloads problems

### ISSUE THREAD

**Issue by Boris-Cui** [url-kaist/kaistviodataset#11]
hallo,
thans for your great work! i want to download your datasets to run in some vslam works. But the download failed. Is there something wrong with link? 

Best Regards
cui

**Comment by zinuok** [comment]
Thank you for your interest in our work. 
Which sequence do you failed? 
If you try to download all of the sequences (= bag files) at once, it may fail for some file because of the network traffic issue.
Please try to download each file sequentially. 
For this, I've uploaded the [shell script](https://github.com/url-kaist/kaistviodataset/blob/main/download.sh) to download all files automatically.

**Comment by Boris-Cui** [comment]
Thank you for your quick response. I want to download all the datasets. I also tried to download each package individually. It failed. I used your shell file to download, which also failed.
