### ISSUE TITLE
can't download dataset

### ISSUE THREAD

**Issue by Divenire1998** [url-kaist/kaistviodataset#7]
Hello~ Thank you for you great job and share~
I want to download the dataset but I find I can't visit the website:
https://urserver.kaist.ac.kr/publicdata/KAIST_VIO_Dataset/kaist_vio_dataset.zip

so I want to know Is there any other channel can help me to get the data, Thank you!

**Comment by zinuok** [comment]
Dear @Divenire1998, 

Thank you for visiting our project and sorry for the inconvenience. 
We also confirmed that the download links could not be accessed from outside due to VPN-related issues in the last few days.

We plan to migrate the data to alternative storage that is accessible. 
This work will be completed in a few days and we will notify you of this issue as soon as it is done.

Thank you for your patience.
Sincerely

**Comment by Divenire1998** [comment]
Dear @zinuok 

Thank you for help and replying, and I can visit the download link now.
