### ISSUE TITLE
Question about hardware sync

### ISSUE THREAD

**Issue by dssdyx** [url-kaist/kaistviodataset#8]
Hi. I also try to use pixhawk4 mini imu and realsense D435i to run vio. But I want to know whether D435i can be synchronized by pixhawk imu. I have saw that px4 user guide has a chapter about "Camera-IMU sync" (https://docs.px4.io/main/en/peripherals/camera.html). It seems like that pixhawk4 mini can trigger camera capture using Main PWM pin. 
I also search some materials about realsense d400 series hw sync information. And I find that D435 can be triggered by external signal using head pin.
I want to know have you configured the devices like above or tried other method to make hardware sync.
If without hardware sync, will the vio algorithm be less accurate and robust?
I hope for your answer, thx!:)

**Comment by zinuok** [comment]
Dear @dssdyx 
Sorry for the late reply.

I just took a look at the link you provided. 
It seems that we can trigger the capture of the real-sense camera as per the link. In fact, I remember seeing cases where time synchronization between real-sense cameras was achieved by connecting an external circuit. 

As you pointed out, the VIO algorithm can be affected by the hardware synchronization between sensors. 
However, to be honest, we didn't perform the hardware synchronization at the time this dataset was created.
Instead, we assumed a sufficiently fast sensor data Hz and delay caused by data acquisition by the hardware itself (more specifically, the time the hardware acquires the data and publishes it as a ROS message) is less than valid time. 

Sincerely,
Jinwoo Jeon

**Comment by dssdyx** [comment]
> Dear @dssdyx Sorry for the late reply.
> 
> I just took a look at the link you provided. It seems that we can trigger the capture of the real-sense camera as per the link. In fact, I remember seeing cases where time synchronization between real-sense cameras was achieved by connecting an external circuit.
> 
> As you pointed out, the VIO algorithm can be affected by the hardware synchronization between sensors. However, to be honest, we didn't perform the hardware synchronization at the time this dataset was created. Instead, we assumed a sufficiently fast sensor data Hz and delay caused by data acquisition by the hardware itself (more specifically, the time the hardware acquires the data and publishes it as a ROS message) is less than valid time. (Also, as you know, most VIO algorithms, like VINS-Fusion, have a time synchronization function for ROS messages from different sensors.)
> 
> Sincerely, Jinwoo Jeon

OK.Thx for your reply.
